name: "rollkit-reth-parallel"

services:
  jwt-init-parallel:
    container_name: jwt-init-parallel
    image: alpine:3.19
    volumes:
      - ./jwttoken:/jwt
    healthcheck:
      test: ["CMD", "test", "-f", "/jwt/jwt.hex"]
      interval: 5s
      timeout: 5s
      retries: 3
    command: >
      /bin/sh -c "mkdir -p /jwt &&
      if [ ! -f /jwt/jwt.hex ]; then
        apk add --no-cache openssl &&
        openssl rand -hex 32 | tr -d '\n' > /jwt/jwt.hex;
      fi"

  rollkit-reth-parallel:
    container_name: rollkit-reth-parallel
    restart: unless-stopped
    image: ghcr.io/rollkit/rollkit-reth:latest
    depends_on:
      jwt-init-parallel:
        condition: service_completed_successfully
    ports:
      - "9011:9001" # metrics
      - "30313:30303" # eth/66 peering
      - "8555:8545" # rpc
      - "8561:8551" # engine
      - "8556:8546" # ws
    volumes:
      - ./chain:/root/chain:ro
      - ./jwttoken:/root/jwt:ro
      - logs-parallel:/root/logs
    entrypoint: /bin/sh -c
    command:
      - |
          rollkit-reth node \
          --chain /root/chain/genesis.json \
          --rollup.disable-tx-pool-gossip \
          --rollup.discovery.v4 \
          --metrics 0.0.0.0:9001 \
          --log.file.directory /root/logs \
          --authrpc.addr 0.0.0.0 \
          --authrpc.port 8551 \
          --authrpc.jwtsecret /root/jwt/jwt.hex \
          --http --http.addr 0.0.0.0 --http.port 8545 \
          --http.api "eth,net,web3,txpool" \
          --ws --ws.addr 0.0.0.0 --ws.port 8546 --ws.api eth,net,web3 \
          --engine.persistence-threshold 0 \
          --engine.memory-block-buffer-target 0 \
          --disable-discovery \
          --txpool.pending-max-count 200000 \
          --txpool.pending-max-size 200 \
          --txpool.queued-max-count 200000 \
          --txpool.queued-max-size 200 \
          --txpool.max-account-slots 2048 \
          --txpool.max-new-txns 2048 \
          --txpool.additional-validation-tasks 16

volumes:
  logs-parallel:
    driver: local 