version: "3.8"

services:
  reth:
    container_name: reth
    restart: unless-stopped
    image: ghcr.io/paradigmxyz/reth:v1.4.6
    ports:
      - "9001:9001" # metrics
      - "30303:30303" # eth/66 peering
      - "8545:8545" # rpc
      - "8551:8551" # engine
      - "8546:8546" # ws
    volumes:
      - ./chain:/root/chain:ro
      - ./jwttoken:/root/jwt:ro
      - logs:/root/logs
    entrypoint: /bin/sh -c
    command:
      - |
          reth node \
          --chain /root/chain/genesis.json \
          --metrics 0.0.0.0:9001 \
          --log.file.directory /root/logs \
          --authrpc.addr 0.0.0.0 \
          --authrpc.port 8551 \
          --authrpc.jwtsecret /root/jwt/jwt.hex \
          --http --http.addr 0.0.0.0 --http.port 8545 \
          --http.api "eth,net,web3,txpool" \
          --ws --ws.addr 0.0.0.0 --ws.port 8546 --ws.api eth,net,web3 \
          --engine.persistence-threshold 0 \
          --engine.memory-block-buffer-target 0 \
          --disable-discovery \
          --txpool.pending-max-count 200000 \
          --txpool.pending-max-size 200 \
          --txpool.queued-max-count 200000 \
          --txpool.queued-max-size 200 \
          --txpool.max-account-slots 2048 \
          --txpool.max-new-txns 2048 \
          --txpool.additional-validation-tasks 16
    networks:
      - rollkit-network

  local-da:
    image: ghcr.io/rollkit/local-da:v0.1.0
    ports:
      - "7980:7980"
    command: ["-listen-all"]
    networks:
      - rollkit-network

  rollkit-evm-single:
    image: ghcr.io/rollkit/rollkit-evm-single:v0.1.5
    depends_on:
      reth:
        condition: service_started
      local-da:
        condition: service_started
    volumes:
      - evm-single-data:/data
    entrypoint: /usr/bin/entrypoint.sh
    environment:
      - EVM_ENGINE_URL=http://reth:8551
      - EVM_ETH_URL=http://reth:8545
      - EVM_JWT_SECRET=f747494bb0fb338a0d71f5f9fe5b5034c17cc988c229b59fd71e005ee692e9bf
      - EVM_GENESIS_HASH=0x593cca87d359c3d0fdc9b67a43f92e1c8eb0da113620225f476eee31a3920e46
      - EVM_BLOCK_TIME=1s
      - EVM_SIGNER_PASSPHRASE=secret
      - DA_ADDRESS=http://local-da:7980 # http://localhost:26658 (Use if not using local-da)
      # - DA_AUTH_TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBbGxvdyI6WyJwdWJsaWMiLCJyZWFkIiwid3JpdGUiXSwiTm9uY2UiOiJQcEswTmhyWi9IY05NWkVtUG9sSXNpRTRDcUpMdE9mbWtBMW0zMWFUaEswPSIsIkV4cGlyZXNBdCI6IjAwMDEtMDEtMDFUMDA6MDA6MDBaIn0.gaWh6tS6Rel1XFYclDkapNnZlaZVjrikCRNBxSDkCGk
      # - DA_NAMESPACE=00000000000000000000000000000000000000000008e5f679bf7116c1
    networks:
      - rollkit-network

volumes:
  logs:
    driver: local
  evm-single-data:

networks:
  rollkit-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.0/24
