name: docker-build-ethermint-debug

on:
  push:
    branches:
      - main
  pull_request:
  release:
    types: [published]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: celestiaorg/ethermint-debug
  TAG_PREFIX: rollmint-

jobs:
  docker-build:
    if: github.event.pull_request.head.repo.full_name == github.repository
    runs-on: "ubuntu-latest"
    permissions:
      contents: write 
      packages: write 
    steps:
      - name: "Checkout source code"
        uses: "actions/checkout@v3"
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17
      - name: up a level
        run: cd .. && pwd
      - name: Clone ethermint repo
        uses: actions/checkout@v3
        with:
          repository: celestiaorg/ethermint
          path: ethermint
      - name: Move Stuff and Tidy
        run: |
          ls
          mv ethermint ..
          cd ..
          cp -R rollmint ethermint
          cd ethermint
          rm -rf .git
          go mod edit -replace=github.com/rollkit/rollkit=./rollmint
          go mod tidy -compat=1.17 -e
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha,prefix=${{ env.TAG_PREFIX }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ../ethermint
          platforms: linux/amd64, linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          file: ../ethermint/docker/debug.Dockerfile
