# lint runs all linters in this repository
# This workflow is triggered by ci_release.yml workflow
name: lint
on:
  workflow_call:
    inputs:
      go-version:
        description: "Go version to use"
        type: string
        required: true

jobs:
  golangci-lint:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ inputs.go-version }}
        # This steps sets the GIT_DIFF environment variable to true
        # if files defined in PATTERS changed
      - uses: technote-space/get-diff-action@v6.1.2
        with:
          # This job will pass without running if go.mod, go.sum, and *.go
          # wasn't modified.
          PATTERNS: |
            **/**.go
            go.mod
            go.sum
      - uses: golangci/golangci-lint-action@v6.0.1
        with:
          version: latest
          args: --timeout 10m
          github-token: ${{ secrets.github_token }}
        if: env.GIT_DIFF

  # hadolint lints the Dockerfile
  hadolint:
    uses: rollkit/.github/.github/workflows/reusable_dockerfile_lint.yml@v0.3.0 # yamllint disable-line rule:line-length
    with:
      dockerfile: test/docker/mockserv.Dockerfile

  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: rollkit/.github/.github/actions/yamllint@v0.3.0

  markdown-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: rollkit/.github/.github/actions/markdown-lint@v0.3.0

  protobuf-lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - run: make proto-gen
      - run: make proto-lint

  cli-docs-lint:
    name: Lint CLI Docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ inputs.go-version }}
      - name: install rollkit cli
        run: make install
      - name: Generate Docs
        run: rollkit docs-gen
      - name: Verify no diff
        run: |
          DIFF=$(git diff)
          if [[ -n "$DIFF" ]]; then
            echo "$DIFF"
            exit 1
          fi
